project_id = "xnpmrafjjqsissbtempj"

[functions.analyze-document]
verify_jwt = false

[functions.extension-sync]
verify_jwt = false

[functions.google-drive-auth]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false